import previsionalFormModel from "./previsionalFormModel";

const {
	formField: {
		reclamante,
		folderId,
		folderName,
		expedienteAdmin,
		prestacion,
		obraSocial,
		fechaAdquisicion,
		fechaAlta,
		haberPagadoAnses,
		haberPagadoAl,
		monedaHaberPagado,
		tieneReajuste,
		fechaAltaReajuste,
		importeReajuste,
		monedaReajuste,
		haberReclamado,
		monedaReclamado,
		fechaDesdeReclamado,
		fechaHastaReclamado,
		fechaCierre,
		criteriosMovilidad,
		tipoTope,
		topeDesde,
		topeHasta,
		tasaInteresSentencia,
	},
} = previsionalFormModel;

const formInitialValues = {
	[reclamante.name]: "",
	[folderId.name]: "",
	[folderName.name]: "",
	[expedienteAdmin.name]: "",
	[prestacion.name]: "",
	[obraSocial.name]: "",
	[fechaAdquisicion.name]: "",
	[fechaAlta.name]: "",
	[haberPagadoAnses.name]: "",
	[haberPagadoAl.name]: "",
	[monedaHaberPagado.name]: "ARS",
	[tieneReajuste.name]: false,
	[fechaAltaReajuste.name]: "",
	[importeReajuste.name]: "",
	[monedaReajuste.name]: "ARS",
	[haberReclamado.name]: "",
	[monedaReclamado.name]: "ARS",
	[fechaDesdeReclamado.name]: "",
	[fechaHastaReclamado.name]: "",
	[fechaCierre.name]: "",
	[criteriosMovilidad.name]: [{ indiceMovilidad: "", fechaDesde: "" }],
	[tipoTope.name]: "",
	[topeDesde.name]: "",
	[topeHasta.name]: "",
	[tasaInteresSentencia.name]: "",
};

export default formInitialValues;
