import compensacionFormModel from "./compensacionFormModel";

const {
	formField: {
		reclamante,
		reclamado,
		tasaDescuentoAnual,
		edadDisolucion,
		edadLimite,
		cantIngresosMensuales,
		probCapacitacion,
		ingresoMax,
		probIngresoMax,
		ingresoReal,
		probIngresoReal,
		isPatrimonio,
		patrimonioInicialReclamado,
		patrimonioInicialReclamante,
		patrimonioFinalReclamado,
		patrimonioFinalReclamante,
		isVivienda,
		cantMesesAtribucionVivienda,
		porcentajeInmuebleOCanon,
		valorCanon,
		cantidadHijos,
		cantidadOtrosFamiliares,
	},
} = compensacionFormModel;

const initialValues = {
	[reclamante.name]: "",
	[reclamado.name]: "",
	[tasaDescuentoAnual.name]: "",
	[edadDisolucion.name]: "",
	[edadLimite.name]: "",
	[cantIngresosMensuales.name]: "",
	[probCapacitacion.name]: "",
	[ingresoMax.name]: "",
	[probIngresoMax.name]: "",
	[ingresoReal.name]: "",
	[probIngresoReal.name]: "",
	[isPatrimonio.name]: false,
	[patrimonioInicialReclamado.name]: "",
	[patrimonioInicialReclamante.name]: "",
	[patrimonioFinalReclamado.name]: "",
	[patrimonioFinalReclamante.name]: "",
	[isVivienda.name]: false,
	[cantMesesAtribucionVivienda.name]: "",
	[porcentajeInmuebleOCanon.name]: "",
	[valorCanon.name]: "",
	[cantidadHijos.name]: "",
	[cantidadOtrosFamiliares.name]: "",
};
export default initialValues;
